### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by ruslangaripov**
This is a PR you **shouldn't** apply without careful checking. You may have your own vision of translation, and I ain't a professional linguist either. For example, you may prefer to stick with *person* instead of *individual*.

Please feel free to reject this PR completely :godmode: That's OK.

Once again: check all changes carefully before you merge this PR.

Here is the log of what I made by this PR (the commit message doesn't contain it since it's an off-topic for it). All changes are written in standard Unix diff format. Every patch has a description where I tried to note why I made a change in the specific way.

*'^M' in my patches stays for CR character, since my local git tool-chain opt to use LF as a line ending*

```
---- log beginning ----
# Patch

diff --git a/projects/GEDKeeper2/GKCore/LangMan.cs b/projects/GEDKeeper2/GKCore/LangMan.cs
index 2c04277..27e7a2e 100644
--- a/projects/GEDKeeper2/GKCore/LangMan.cs
+++ b/projects/GEDKeeper2/GKCore/LangMan.cs
@@ -840,7 +840,7 @@ namespace GKCore
             /* 042 */ "&Horizontal tile",
             /* 043 */ "&Vertical tile",
             /* 044 */ "&Minimize all",
-            /* 045 */ "&Arrange all",
+            /* 045 */ "&Rearrange all",^M
             /* 046 */ "Internet resources...",
             /* 047 */ "Kinship terms...",
             /* 048 */ "FAQ...",

# Description

Here are explanations of the words meaning given in Oxford Dictionary
of English, 3rd Edition:

arrange
put (things) in a neat, attractive, or required order

rearrange
change the position of

And GK's ex-"Arrange all" menu item just changes the position of opened
windows. There's no required order in this case.

# Patch

@@ -866,42 +866,42 @@ namespace GKCore
             /* 068 */ "Female",
             /* 069 */ "Undetermined",
             /* 070 */ "The file is modified. Save?",
-            /* 071 */ "Found the specified parent family \"{0}\". Attach to it a child?",
-            /* 072 */ "Remove personal record \"{0}\"?",
-            /* 073 */ "Remove family record \"{0}\"?",
-            /* 074 */ "Remove note record \"{0}\"?",
-            /* 075 */ "Remove source record \"{0}\"?",
-            /* 076 */ "Remove multimedia record \"{0}\"?",
-            /* 077 */ "Remove repository record \"{0}\"?",
-            /* 078 */ "Remove group record \"{0}\"?",
-            /* 079 */ "Remove research record \"{0}\"?",
-            /* 080 */ "Remove task record \"{0}\"?",
-            /* 081 */ "Remove communication record \"{0}\"?",
-            /* 082 */ "Remove location record \"{0}\"?",
+            /* 071 */ "The specified parent has an existed family \"{0}\". Do you want to add the child to that family?",^M
+            /* 072 */ "Remove individual \"{0}\"?",^M
+            /* 073 */ "Remove family \"{0}\"?",^M
+            /* 074 */ "Remove note \"{0}\"?",^M
+            /* 075 */ "Remove source \"{0}\"?",^M
+            /* 076 */ "Remove multimedia \"{0}\"?",^M
+            /* 077 */ "Remove repository \"{0}\"?",^M
+            /* 078 */ "Remove group \"{0}\"?",^M
+            /* 079 */ "Remove research \"{0}\"?",^M
+            /* 080 */ "Remove task \"{0}\"?",^M
+            /* 081 */ "Remove communication \"{0}\"?",^M
+            /* 082 */ "Remove location \"{0}\"?",^M
             /* 083 */ "Address",
             /* 084 */ "Events",
-            /* 085 */ "Surname",
-            /* 086 */ "Name",
+            /* 085 */ "Last name",^M
+            /* 086 */ "First name",^M
             /* 087 */ "Patronymic",
             /* 088 */ "Sex",
             /* 089 */ "Nickname",
-            /* 090 */ "Surname prefix",
+            /* 090 */ "Last name prefix",^M
             /* 091 */ "Name prefix",
             /* 092 */ "Name suffix",
             /* 093 */ "Patriarch",
             /* 094 */ "Bookmark",
             /* 095 */ "Association",
             /* 096 */ "Relation",
-            /* 097 */ "Person",
-            /* 098 */ "Accept",
+            /* 097 */ "Individual",^M
+            /* 098 */ "Apply",^M
             /* 099 */ "Cancel",
             /* 100 */ "Close",
             /* 101 */ "Select",
             /* 102 */ "Append",
-            /* 103 */ "New personal record",
-            /* 104 */ "Edit personal record",
-            /* 105 */ "Check the sex",
-            /* 106 */ "Select record",
+            /* 103 */ "New individual",^M
+            /* 104 */ "Edit individual",^M
+            /* 105 */ "Checking of sex",^M
+            /* 106 */ "Selecting a record",^M
             /* 107 */ "Source citation",
             /* 108 */ "User reference",
             /* 109 */ "Note",

# Description

"Found the specified parent family \"{0}\". Attach to it a child?" vs.
"The specified parent has an existed family \"{0}\". Do you want to add
the child to that family?"

I believe this is more correct.

"Remove personal record \"{0}\"?" vs. "Remove individual \"{0}\"?"

You've previously translated "Персоны" as "Individuals". That's why I
use "individual" here too. GK must be a consistent app :smiling_imp:
† A note from Collins Cobuild Advanced Learner’s English Dictionary:
> An individual is a person
Thus, those words are synonyms.

Now about "record" words. Russian text doesn't have it. Why does
Egnlish have it? :smiling_imp:

"Last name" and "Family name" will be more clear/usual for English users
I believe.

"Accept" vs. "Apply"

This is more usual to see "Apply" text on command buttons.

# Patch

@@ -915,37 +915,37 @@ namespace GKCore
             /* 117 */ "Wife",
             /* 118 */ "Status",
             /* 119 */ "Childs",
-            /* 120 */ "Detach link on husband?",
-            /* 121 */ "Detach link on wife?",
-            /* 122 */ "Detach link on child?",
+            /* 120 */ "Detach link to husband?",^M
+            /* 121 */ "Detach link to wife?",^M
+            /* 122 */ "Detach link to child?",^M
             /* 123 */ "Birth date",
             /* 124 */ "Death date",
-            /* 125 */ "Restriction",
+            /* 125 */ "Security restriction",^M
             /* 126 */ "Title",
             /* 127 */ "Members",
-            /* 128 */ "Group edit",
-            /* 129 */ "Detach link on member?",
+            /* 128 */ "Edit group",^M
+            /* 129 */ "Detach link to member?",^M
             /* 130 */ "view",
             /* 131 */ "Stage",
-            /* 132 */ "Telephone",
-            /* 133 */ "eMail",
+            /* 132 */ "Telephone number",^M
+            /* 133 */ "email",^M
             /* 134 */ "Web site",
             /* 135 */ "Repository",
             /* 136 */ "Progress",
-            /* 137 */ "Time passed",
-            /* 138 */ "Time remain",
-            /* 139 */ "Time total",
+            /* 137 */ "Elapsed time",^M
+            /* 138 */ "Remaining time",^M
+            /* 139 */ "Total time",^M
             /* 140 */ "Date",
             /* 141 */ "Text",
             /* 142 */ "Short title",
             /* 143 */ "Author",
-            /* 144 */ "Publication",
+            /* 144 */ "Published",^M
             /* 145 */ "Common",
-            /* 146 */ "Detach link on repository?",
+            /* 146 */ "Detach link to repository?",^M
             /* 147 */ "Store type",
             /* 148 */ "File",
             /* 149 */ "View",
-            /* 150 */ "For selected type of store is not enabled extension",
+            /* 150 */ "Extension mode is not enabled for selected store type",^M
             /* 151 */ "Father",
             /* 152 */ "Mother",
             /* 153 */ "Parents",

# Description

One made link **to** someone.

There's one question remained: why "Detach" if the Russain text
contains "Remove" word?

# Patch

@@ -963,7 +963,7 @@ namespace GKCore
             /* 165 */ "Roman",
             /* 166 */ "Unknown",
             /* 167 */ "Summary",
-            /* 168 */ "Others",
+            /* 168 */ "Other",^M
             /* 169 */ "Submission",
             /* 170 */ "Submitter",
             /* 171 */ "Location",

# Description

Why should we use a plural noun?

# Patch

@@ -982,21 +982,21 @@ namespace GKCore
             /* 184 */ "Theme",
             /* 185 */ "Corresponder",
             /* 186 */ "Group",
-            /* 187 */ "Detach link on task?",
-            /* 188 */ "Detach link on communication?",
-            /* 189 */ "Detach link on group?",
-            /* 190 */ "Research edit",
-            /* 191 */ "Task edit",
-            /* 192 */ "Communication edit",
+            /* 187 */ "Detach link to task?",^M
+            /* 188 */ "Detach link to communication?",^M
+            /* 189 */ "Detach link to group?",^M
+            /* 190 */ "Edit research",^M
+            /* 191 */ "Edit task",^M
+            /* 192 */ "Edit communication",^M
             /* 193 */ "Error",
             /* 194 */ "Lua start failed!",
-            /* 195 */ "Date format invalid",
+            /* 195 */ "Date format is invalid",^M
             /* 196 */ "Country",
             /* 197 */ "State",
             /* 198 */ "City",
             /* 199 */ "Postal code",
-            /* 200 */ "Telephones",
-            /* 201 */ "EMails",
+            /* 200 */ "Telephone numbers",^M
+            /* 201 */ "Emails",^M
             /* 202 */ "Web sites",
             /* 203 */ "Value",
             /* 204 */ "Event",

# Description

See above about "link on".

"Invalid" is an adjective here.

# Patch

@@ -1005,22 +1005,22 @@ namespace GKCore
             /* 207 */ "Agency",
             /* 208 */ "Female",
             /* 209 */ "Male",
-            /* 210 */ "Not selected a personal record",
-            /* 211 */ "For this person is not defined the sex.",
-            /* 212 */ "For this person is not families.",
-            /* 213 */ "Estimated number of ancestors {0} more than permissible limits.",
-            /* 214 */ "Estimated number of descendants {0} more than permissible limits.",
+            /* 210 */ "An individual record is not selected.",^M
+            /* 211 */ "This individual has no sex defined.",^M
+            /* 212 */ "This indiviaul has no families.",^M
+            /* 213 */ "Estimated number of ancestors {0} is more than permissible limits.",^M
+            /* 214 */ "Estimated number of descendants {0} is more than permissible limits.",^M
             /* 215 */ "Generations visible:",
             /* 216 */ "unlimited",
             /* 217 */ "Spouse",
             /* 218 */ "Marriage date",
-            /* 219 */ "Detach link on father?",
-            /* 220 */ "Detach link on mother?",
-            /* 221 */ "Detach link on spouse?",
-            /* 222 */ "Detach link on parents?",
+            /* 219 */ "Detach link to father?",^M
+            /* 220 */ "Detach link to mother?",^M
+            /* 221 */ "Detach link to spouse?",^M
+            /* 222 */ "Detach link to parents?",^M
             /* 223 */ "All",
-            /* 224 */ "Only ancestors",
-            /* 225 */ "Only descendants",
+            /* 224 */ "Ancestors only",^M
+            /* 225 */ "Descendants only",^M
             /* 226 */ "Trace root",
             /* 227 */ "Edit",
             /* 228 */ "Add family",

# Description

See above.

# Patch

@@ -1036,9 +1036,9 @@ namespace GKCore
             /* 238 */ "family",
             /* 239 */ "Namesakes",
             /* 240 */ "Remove the event?",
-            /* 241 */ "Detach link on note?",
-            /* 242 */ "Detach link on multimedia?",
-            /* 243 */ "Detach link on source?",
+            /* 241 */ "Detach link to note?",^M
+            /* 242 */ "Detach link to multimedia?",^M
+            /* 243 */ "Detach link to source?",^M
             /* 244 */ "Remove the association?",
             /* 245 */ "Remove the user reference?",
             /* 246 */ "Loading of gedcom failed.",

# Description

See above.

# Patch

@@ -1048,7 +1048,7 @@ namespace GKCore
             /* 250 */ "Interface",
             /* 251 */ "Trees",
             /* 252 */ "Pedigrees",
-            /* 253 */ "Coding of save",
+            /* 253 */ "Files encoding",^M
             /* 254 */ "Addresses",
             /* 255 */ "Mails",
             /* 256 */ "Webs",

# Description

That's more correct.

# Patch

@@ -1059,27 +1059,27 @@ namespace GKCore
             /* 261 */ "Login",
             /* 262 */ "Password",
             /* 263 */ "The password is not specified",
-            /* 264 */ "Show on startup",
+            /* 264 */ "Show tips on startup",^M
             /* 265 */ "Language",
             /* 266 */ "All lists",
-            /* 267 */ "List of persons",
-            /* 268 */ "Names format",
+            /* 267 */ "List of individuals",^M
+            /* 268 */ "Name format in lists",^M
             /* 269 */ "Surname_Name_Patronymic",
             /* 270 */ "Surname; Name_Patronymic",
             /* 271 */ "Surname; Name; Patronymic",
-            /* 272 */ "Date format",
-            /* 273 */ "Places with address",
+            /* 272 */ "Date format in lists",^M
+            /* 273 */ "Include address into place text",^M
             /* 274 */ "Highlight unparented",
             /* 275 */ "Highlight unmarried",
             /* 276 */ "Default values",
-            /* 277 */ "View of tree",
-            /* 278 */ "Different lines",
+            /* 277 */ "Show individuals in tree",^M
+            /* 278 */ "Separate lines",^M
             /* 279 */ "Only years",
-            /* 280 */ "Kinship",
-            /* 281 */ "Signs visible",
+            /* 280 */ "Relation degree",^M
+            /* 281 */ "Additional symbols",^M
             /* 282 */ "Tree decorative",
-            /* 283 */ "Portraits visible",
-            /* 284 */ "Childless exclude",
+            /* 283 */ "Show portraits",^M
+            /* 284 */ "Exclude one who died while was child",^M
             /* 285 */ "Decor",
             /* 286 */ "Man",
             /* 287 */ "Woman",

# Description

Russian origin contains "Показывать при старте подсказки" text. Your
English text didn't specify **what** to show on startup. I've fixed it.

# Patch

@@ -1088,22 +1088,22 @@ namespace GKCore
             /* 290 */ "Divorcee wife",
             /* 291 */ "Font",
             /* 292 */ "Pedigree generation",
-            /* 293 */ "Include attributes",
+            /* 293 */ "Include attributes of individuals",^M
             /* 294 */ "Include notes",
             /* 295 */ "Include sources",
             /* 296 */ "Pedigree format",
             /* 297 */ "Excess",
             /* 298 */ "Compact",
-            /* 299 */ "Record jump",
-            /* 300 */ "Record move up",
-            /* 301 */ "Record move down",
+            /* 299 */ "Jump to a record",^M
+            /* 300 */ "Move record up",^M
+            /* 301 */ "Move record down",^M
             /* 302 */ "Full name",
             /* 303 */ "Birth place",
             /* 304 */ "Death place",
             /* 305 */ "Residence",
             /* 306 */ "Age",
-            /* 307 */ "Life expectancy",
-            /* 308 */ "Days for birth",
+            /* 307 */ "Duration of life",^M
+            /* 308 */ "Days before birth",^M
             /* 309 */ "Religion",
             /* 310 */ "Nationality",
             /* 311 */ "Education",
@@ -1127,7 +1127,7 @@ namespace GKCore
             /* 329 */ "Immigration",
             /* 330 */ "Census",
             /* 331 */ "Will",
-            /* 332 */ "Probate",
+            /* 332 */ "Probate of will",^M
             /* 333 */ "Death",
             /* 334 */ "Burial",
             /* 335 */ "Cremation",
@@ -1181,7 +1181,7 @@ namespace GKCore
             /* 383 */ "Next",
             /* 384 */ "<?>",
             /* 385 */ "Next",
-            /* 386 */ "You know what ...",
+            /* 386 */ "You know that ...",^M
             /* 387 */ "Load and search for places",
             /* 388 */ "(not selected)",
             /* 389 */ "Sample",
@@ -1189,7 +1189,7 @@ namespace GKCore
             /* 391 */ "Places of birth",
             /* 392 */ "Places of death",
             /* 393 */ "Places of residence",
-            /* 394 */ "Only the chosen",
+            /* 394 */ "Only selected",^M
             /* 395 */ "Save image...",
             /* 396 */ "The format is not supported",
             /* 397 */ "Error loading data.",
@@ -1202,7 +1202,7 @@ namespace GKCore
             /* 404 */ "Before",
             /* 405 */ "After",
             /* 406 */ "Between",
-            /* 407 */ "Period to",
+            /* 407 */ "Period before",^M
             /* 408 */ "Period from",
             /* 409 */ "Period between",
             /* 410 */ "About",
@@ -1267,7 +1267,7 @@ namespace GKCore
             /* 469 */ "Correspondence",
             /* 470 */ "Correction IDs",
             /* 471 */ "Check format",
-            /* 472 */ "Requires correction of identity records, continue?",
+            /* 472 */ "Correction of identity records is required, continue?",^M
             /* 473 */ "Number of objects in the master database: {0}",
             /* 474 */ "Synchronization is complete.",
             /* 475 */ "Search the patriarchs",
@@ -1283,8 +1283,8 @@ namespace GKCore
             /* 485 */ "Pedigree",
             /* 486 */ "Parameter",
             /* 487 */ "Total",
-            /* 488 */ "Mans",
-            /* 489 */ "Womans",
+            /* 488 */ "Men",^M
+            /* 489 */ "Women",^M
             /* 490 */ "Fields filter",
             /* 491 */ "Year",
             /* 492 */ "PDF files (*.pdf)|*.pdf",
@@ -1295,15 +1295,15 @@ namespace GKCore
             /* 497 */ "Cutting off the branches",
             /* 498 */ "not",
             /* 499 */ "on years",
-            /* 500 */ "in selected persons",
+            /* 500 */ "in selected individuals",^M
             /* 501 */ "- all -",
             /* 502 */ "- not -",
             /* 503 */ "- any -",
             /* 504 */ "Master-base",
-            /* 505 */ "Other base",
+            /* 505 */ "Database updating",^M
             /* 506 */ "[current base]",
-            /* 507 */ "There is a filter on the source. To make the source in a new personal record?",
-            /* 508 */ "There is a filter in the group. To make a group in a new personal record?",
+            /* 507 */ "There is a filter by a source. Do you want to add the source to a new individual?",^M
+            /* 508 */ "There is a filter by a group. Do you want to add the group to a new individual?",^M
             /* 509 */ "Duplicates search",
             /* 510 */ "Invalid value",
             /* 511 */ "Operation",
@@ -1312,22 +1312,22 @@ namespace GKCore
             /* 514 */ "Split database",
             /* 515 */ "Merge records",
             /* 516 */ "Import pedigrees",
-            /* 517 */ "Check the connection of families",
+            /* 517 */ "Check connection of families",^M
             /* 518 */ "Check database",
             /* 519 */ "Search the patriarchs",
             /* 520 */ "Manage places",
             /* 521 */ "Matching...",
-            /* 522 */ "Check the connection of families",
+            /* 522 */ "Check connection of families",^M
             /* 523 */ "all",
-            /* 524 */ "only living",
-            /* 525 */ "only dead",
-            /* 526 */ "In living up to",
-            /* 527 */ "only men",
-            /* 528 */ "only women",
+            /* 524 */ "living only ",^M
+            /* 525 */ "dead only",^M
+            /* 526 */ "Lived before",^M
+            /* 527 */ "men only",^M
+            /* 528 */ "women only",^M
             /* 529 */ "Mask of name",
             /* 530 */ "Mask of residence",
             /* 531 */ "Mask of the facts",
-            /* 532 */ "Only the patriarchs",
+            /* 532 */ "Patriarchs only",^M
             /* 533 */ "Date is invalid",
             /* 534 */ "People",
             /* 535 */ "Years",
@@ -1337,11 +1337,11 @@ namespace GKCore
             /* 539 */ "Living",
             /* 540 */ "Dead",
             /* 541 */ "Average age",
-            /* 542 */ "Average life expectancy",
+            /* 542 */ "Life expectancy",^M
             /* 543 */ "Average number of children",
-            /* 544 */ "Average age of first child birth",
+            /* 544 */ "Average age of the first child birth",^M
             /* 545 */ "Average number of marriages",
-            /* 546 */ "Average age of marriage",
+            /* 546 */ "Average age of celebration of marriage",^M
             /* 547 */ "Number of ancestors",
             /* 548 */ "Number of descendants",
             /* 549 */ "Number of generations of descendants",
@@ -1369,7 +1369,7 @@ namespace GKCore
             /* 571 */ "The accuracy of the name, %",
             /* 572 */ "Years inaccuracy",
             /* 573 */ "Repair",
-            /* 574 */ "Generations of not less than",
+            /* 574 */ "Generations of descendants, not less than",^M
             /* 575 */ "Set a sign",
             /* 576 */ "Register in list of locations",
             /* 577 */ "Similar surnames:",
@@ -1379,18 +1379,18 @@ namespace GKCore
             /* 581 */ "Problem",
             /* 582 */ "Solve",
             /* 583 */ "Perhaps died (age {0})",
-            /* 584 */ "Not determine the sex",
-            /* 585 */ "Year of birth more than a year of death",
+            /* 584 */ "Sex is undefined",^M
+            /* 585 */ "Year of birth more than year of death",^M
             /* 586 */ "The first marriage at the age of {0} years?",
             /* 587 */ "The first child was born at the age of {0} years?",
             /* 588 */ "Descendants",
             /* 589 */ "Generations",
             /* 590 */ "Number of links",
-            /* 591 */ "Preparing places",
+            /* 591 */ "Processing places",^M
             /* 592 */ "The place is already in the locations list",
             /* 593 */ "DNA markers",
-            /* 594 */ "��.����.�������� �������� �� �� ��������",
-            /* 595 */ "��.����.�������� �������� �� �� �������",
+            /* 594 */ "Ср.возр.рождения первенца на ДР родителя",^M
+            /* 595 */ "Ср.возр.рождения первенца на ДР ребенка",^M
             /* 596 */ "Empty family record",
             /* 597 */ "backup each file revision",
             /* 598 */ "Loading",

# Description

Pretty self-descriptive I believe.

For the patch applied from the line 1379. As you can see strings having
594 and 595 identifiers, is not translated. And I couldn't understand
what that means, sorry.

# Patch

@@ -1410,11 +1410,11 @@ namespace GKCore
             /* 612 */ "Privacy",
             /* 613 */ "Send the error log",
             /* 614 */ "Charts",
-            /* 615 */ "The size of the window",
+            /* 615 */ "Fit window size",^M
             /* 616 */ "Zoom in",
             /* 617 */ "Zoom out",
-            /* 618 */ "To setup the fact of death",
-            /* 619 */ "To determine the sex",
+            /* 618 */ "Ascertain a fact of death",^M
+            /* 619 */ "Determine a sex",^M
             /* 620 */ "Plugins",
             /* 621 */ "Auto-trace relationships",
             /* 622 */ "No matches found",
@@ -1426,7 +1426,7 @@ namespace GKCore
             /* 628 */ "Reset",
             /* 629 */ "Field",
             /* 630 */ "Condition",
-            /* 631 */ "Not specified the source",
+            /* 631 */ "Source is not specified",^M
             /* 632 */ "Slideshow",
             /* 633 */ "Previous record",
             /* 634 */ "Next record",
@@ -1437,17 +1437,17 @@ namespace GKCore
             /* 639 */ "Names",
             /* 640 */ "Name-nickname",
             /* 641 */ "Birth name",
-            /* 642 */ "In immigration",
+            /* 642 */ "Immigrated",^M
             /* 643 */ "Maiden name",
             /* 644 */ "Marriage name",
-            /* 645 */ "To delete a name?",
-            /* 646 */ "You cannot delete the alone name",
+            /* 645 */ "Delete a name?",^M
+            /* 646 */ "You cannot delete the only name",^M
             /* 647 */ "Quote",
-            /* 648 */ "To bookmark the merged records",
-            /* 649 */ "Show dates calendar",
+            /* 648 */ "Place a bookmark on merged records",^M
+            /* 649 */ "Show calendar near dates",^M
             /* 650 */ "Duplicate record",
-            /* 651 */ "Attention: when you duplicate personal records, family links and associations are not copied",
-            /* 652 */ "Show the signatures of date type",
+            /* 651 */ "Attention: if you duplicate an individual, family links and associations are not copied",^M
+            /* 652 */ "Show date type",^M
             /* 653 */ "Create a new tree file",
             /* 654 */ "Open the tree file",
             /* 655 */ "Save tree file",
@@ -1486,17 +1486,17 @@ namespace GKCore
             /* 688 */ "Select or add wife",
             /* 689 */ "Disconnect wife",
             /* 690 */ "Go to the record of the wife",
-            /* 691 */ "Choose a personal record",
+            /* 691 */ "Choose an individual",^M
             /* 692 */ "Select or add a location",
             /* 693 */ "Remove the link to the place",
             /* 694 */ "Show the map",
             /* 695 */ "Select or add a record of source",
             /* 696 */ "Select the target record",
-            /* 697 */ "For storage types \"file\" and \"store\" the new DB file you need to save",
+            /* 697 */ "If you use \"file\" or \"store\" storage type, you have to save new database file before continue",^M
             /* 698 */ "A file with the same name already exists in the repository",
-            /* 699 */ "It's not GEDSEC-compatible file",
-            /* 700 */ "This person have a few families. Children should be added via the spouses.",
-            /* 701 */ "An error of export to Excel",
+            /* 699 */ "It's not a GEDSEC-compatible file",^M
+            /* 700 */ "This individual has a few families. Children should be added via the spouses.",^M
+            /* 701 */ "Export to Excel failed",^M
             /* 702 */ "Specific filter",
             /* 703 */ "Display lines",
             /* 704 */ "Type of comparison",
@@ -1504,13 +1504,13 @@ namespace GKCore
             /* 706 */ "Comparing with another database",
             /* 707 */ "Analysis (experimental)",
             /* 708 */ "Compare",
-            /* 709 */ "Ignore the date",
+            /* 709 */ "Ignore dates",^M
             /* 710 */ "Chart",
             /* 711 */ "Family book",
             /* 712 */ "Table of contents",
-            /* 713 */ "Personal records",
+            /* 713 */ "Records of individuals",^M
             /* 714 */ "Directories",
-            /* 715 */ "Gender is not defined by a man named \"{1}\". It's male gender?",
+            /* 715 */ "Unable to auto-detect gender using name \"{1}\". Is it male gender?",^M
             /* 716 */ "Autosave every",
             /* 717 */ "minutes",
             /* 718 */ "Including number of generations",

# Description

Pretty self-descriptive I believe.

---- log ending ----
```

Signed-off-by: Ruslan Garipov <brigadir15@gmail.com>

### CODE REVIEW

**Comment by ruslangaripov** [comment]
Please think about limiting width of source code text :smiling_imp: You may use old school 80 characters limit. In my 'meramic' I stick with that width -- very useful!

Here is an example:

```cpp
#pragma once
#include <cstdint>

//------------------------------------------------------------------------------
// `lssb_t` template.
// Searches the least significant set bit using compiler.
//
// Classic C++ solution comes first.
// It uses `std::uint64_t` as underlying data type. Result is 1-based bit index.
//------------------------------------------------------------------------------
template <std::uint64_t V, std::uint64_t R = V % 2, bool I = false>
struct lssb_t: lssb_t<V / 2, V % 2, true>
{
  typedef lssb_t<V / 2, V % 2, true> base_class_t;
  static const std::uint64_t index = base_class_t::index + 1;
};

template <std::uint64_t V>
struct lssb_t<V, 1, true>
{
  static const std::uint64_t index = 0;
};

template <std::uint64_t V>
struct lssb_t<V, 1, false>
{
  static const std::uint64_t index = 1;
};

template <bool I>
struct lssb_t<0, 0, I>
{
  static const std::uint64_t index = 0;
};

//------------------------------------------------------------------------------
// Here comes C++11 solution. It operates by data having template argument type,
// that shall have integral or unscoped enumeration type (5.6.2 [expr.mul],
// 5.8.1 [expr.shift]).
// Result is 1-based bit index.
//------------------------------------------------------------------------------
template <typename T>
constexpr T lssb(const T value)
{
  return static_cast<T> (!value ? 0 : ((value % 2) ? 1 : lssb(value >> 1) + 1));
}
```

Even GitHub GUI likes it. But there is the horizontal scroll bar in my log in the PR message. Had you limit the code width, it doesn't appear.

**Comment by Serg-Norseman** [comment]
I think :)

**Comment by Serg-Norseman** [comment]
I have 6 downloads from the US (from SF). And you know the language better than me, so I'll take almost everything, just examine was a couple of points that confused me

**Comment by ruslangaripov** [comment]
> I have 6 downloads from the US (from SF).

:+1:

**Pull request merged**
