### PR TITLE
Make a circle chart scrollable

### PR DESCRIPTION
**Pull request by ruslangaripov**
PR title is self explanatory. This PR make a circle chart scrollable. This causes the following changes...

...in GUI:

- A circle chart does **not** have a fixed center anymore.
- A circle chart's left edge is aligned with a window's left edge, and chart's top edge is aligned with window's top edge.

...and the following changes in the code:

 - A circle chart renders it content using point (0, 0) as circle center point.
- A circle chart uses transformation model via transformation matrices to make the chart visible in the window.

@Serg-Norseman, there's one question I have solved without previously asking you, sorry. It's here:

The member `CircleChart.DrawPersonName` at file 'projects/GEDKeeper2/GKUI/Charts/CircleChart.cs':

```csharp
                            gfx.DrawString(givn, Font, fCircleBrushes[8], -sizeF2.Width / 2f, -sizeF2.Height / 2f);
                        }

                    } else if (wedgeAngle < 200) {

                        if (ArcText) {
                            SizeF sizeF = gfx.MeasureString(surn, Font);
```

[direct link to the code](https://github.com/Serg-Norseman/GEDKeeper/blob/master/projects/GEDKeeper2/GKUI/Charts/CircleChart.cs#L362).

The member `CircleChart.DrawPersonName` uses 200° as **the last** limit for drawing segment text. Therefore, if `wedgeAngle` is above 199° **no text is rendered**. Here is my question: is it by design? And sorry, I replaced the limit with 361° in f0ea02e. Now a big or even full-circle segment has its text visible. Upside down, of course, but it **is** visible at least.

ChangeLog:

2017-01-31 Ruslan Garipov <brigadir15@gmail.com>

* projects/GEDKeeper2/GKUI/Charts/AncestorsCircle.cs: Segments are calculated in member `CreateCircleSegment`; all callers changed. Renamed some local variables. Refactored and improved some code.
* projects/GEDKeeper2/GKUI/Charts/DescendantsCircle.cs: Likewise.
* projects/GEDKeeper2/GKUI/Charts/CircleChart.cs: Removed fixed center point; all callers changed. Content is always rendered at (0, 0). Added members `fBounds`, `GetCenter`. Segment text is drawn even for sectors larger than 200°.
* projects/GEDKeeper2/GKUI/Charts/TreeChartBox.cs: Replaced tabs with spaces.
* projects/GKCommon/GEDCOM/GEDCOMFamilyRecord.cs: Added a FIXME commentary.
* projects/GEDKeeper2/GKUI/Charts/CustomChart.cs: Added member `CreateCircleSegment(GraphicsPath, int, int, float, float, float)`.

### CODE REVIEW

**Comment by Serg-Norseman** [comment]
I looked in action. Good :) But it seems to me that the charts would do well to draw on the center window, if the chart is smaller. What do you think? I also need to soon tie print for these charts.

**Comment by ruslangaripov** [comment]
Why not...

So, I am about to implement it in the following way: if a chart dimension (horizontal or/and vertical) is smaller than the window client size dimension, the code centers the chart along the axis. If not (scrollbar is required) -- the chart is aligned by its left/top edge. Thus, jitter of the rendered image is possible when a scrollbar appears/disappears. Okay for the implementation?

Printing is not a problem while you control the GDI+ rendering context.

**Comment by Serg-Norseman** [comment]
Print already has a well-established method for TreeChart. Just need to transfer methods and to adapt

**Comment by ruslangaripov** [comment]
Okay, I will try to adopt the existing printing.

What about chart alignment I have just proposed? 😀

**Comment by Serg-Norseman** [comment]
Think it fits and all will be well 👍

**Comment by ruslangaripov** [comment]
OK, I'm starting the work 🏃

**Comment by ruslangaripov** [comment]
Sorry for the pollution I had made in this topic -- I observed new commit ba2b6b6 too late :confused: I had to git-rebase my changes.

**Pull request merged**
