### PR TITLE
Fix drawing horisontal lines to adopted child in descendants diagram

### PR DESCRIPTION
**Pull request by hazzik**
image

For the discussion: Should the horizontal line to the third child be dotted or not?

### CODE REVIEW

**Comment by Serg-Norseman** [comment]
Is the third child adopted?

**Comment by Serg-Norseman** [comment]
The quality of the code is good! It is not clear - initially, in the database, the third child is adopted or not. Only along the lines, the first and the third?

**Comment by Serg-Norseman** [comment]
If the third child, like the first, is adopted, then I like this solution in the code and the view of the diagram more.

**Review by Serg-Norseman — COMMENTED** [review]
Nice code. And in appearance, I like this one more.

**Comment by hazzik** [comment]
Yes, third and first children are adopted.

**Pull request merged**
