### PR TITLE
Deploy scripts

### PR DESCRIPTION
**Pull request by Dreamer451**
You deserve the credit as Publisher in the `Add/Remove Programs` applet [(604e54d)](https://github.com/Serg-Norseman/GEDKeeper/commit/604e54d15c8ac94bd408a78706df3a5381668ff6).

I know [1cd9897](https://github.com/Serg-Norseman/GEDKeeper/commit/1cd9897f39ae71e71aa9de63465c8b9a82cd3453) is extensive, but it would be handy for people like me who have not been on the project since day 1. In hindsight I should have made this a separate pull request since these 2 commits have little in common. Oh well.

### CODE REVIEW

**Comment by Serg-Norseman** [comment]
Oh-ho-ho, Kevin! :) Branches are not folders :) feature-deploy - I certainly will accept, later, but nevertheless, please read about the branches in the manuals on the git.

I will accept this pull request later and combine the files back with their main originals.

**Comment by Dreamer451** [comment]
Tired of me yet? Thank you for having more patience with me than I would
with me. My heart is in the right place.

 

Kevin Sandal

 

"It isn't the mountains ahead to climb that wear you out; it's the pebble in
your shoe."
-- Muhammad Ali

**Comment by Serg-Norseman** [comment]
Somehow we can cope, by joint efforts :)

**Comment by Dreamer451** [comment]
I did the following:
1. Moved the deploy scripts I edited to a safe location outside of the repository (using File Manager).
2. Deleted the `feature-deploy` folder.
3. Created a new branch under `master` called `deploy-scripts`.
4. Used File Manager to copy the deploy scripts from the safe location over the existing deploy scripts.

So the deploy scripts show as modified and I could commit them. However, all the Lua scripts in the `samples\scripts` folder were also marked as changed. Why would that be? Diff does not show any modifications.
I then deleted my branch I made in step 3 (--hard) but the branch still shows and the scripts still show as having been changed. The deploy scripts returned to their previous state.
What am I doing wrong?

**Comment by ruslangaripov** [comment]
> Moved the deploy scripts I edited to a safe location outside of the repository (using File Manager).
> Used File Manager to copy the deploy scripts from the safe location over the existing deploy scripts.

You shouldn't do that.  It was enough to `git-branch(1)` or `git-checkout(1)`.  For example:

```sh
$ git checkout -b feature-deploy
```

Then you can make changes to files.  In place.

> all the Lua scripts in the samples\scripts folder were also marked as changed. {elided} Diff does not show any modifications.

Where did you see those "marked as changed"?  `git-status(1)` I believe?  If so, what statuses the script files have?  \`\`New'' (or \`\`?'' (*untracked*))?  Or may be \`\`Staged''?  You know, simple `git diff` may not show all your changes (read the manual page, at least its \`\`Examples'' section).

> I then deleted my branch I made in step 3 (--hard) but the branch still shows

I believe you made `git reset --hard`?  This doesn't remove a branch.  This resets the index and working tree.  This is why "the deploy scripts returned to their previous state" (you've just reset the working tree).

> the scripts still show as having been changed

Because/if this happened after `git reset --hard`, the scripts files are "untracked" ones.  As why this happened -- I don't know.

**Comment by ruslangaripov** [comment]
> I did the following

I mean, if I wanted to change deploy/gk2_win_portable.cmd and deploy/gk2_win_setup.nsi files, I would do something like this:

```sh
$ cd gedkeeper_repo
$ git pull --ff-only {@Serg-Norseman's remote} master
$ git checkout -b deploy_scripts
$ vim deploy/gk2_win_portable.cmd deploy/gk2_win_setup.nsi
$ git commit -S -s -a -e -m "Improve some deploy scripts"
$ git push {my remote} deploy_scripts
```

Then I would create new pull request on this site to merge my remote's \`\`deploy_scripts'' to @Serg-Norseman's \`\`master''.  After that pull request is merged, I will remove local and remote \`\`deploy_scirpts'' branches.

If I need to be sure that my local repository is completely synchronized with the original, yes, I may issue `git reset --hard HEAD` after `git-pull(1)` above.  But remember: `git reset --hard` is a dangerous command sometimes :-D  Because it does reset your working tree.  There's no way back after that, except you don't have a file system snapshot.

G'luck and happy hacking!  :-)

**Comment by Serg-Norseman** [comment]
Well, in principle, Ruslan told everything right, I have nothing to add ...

**Comment by Dreamer451** [comment]
You have given me much to think about. Thank you.

**Pull request closed without merging**
