### PR TITLE
Build scripts: error management

### PR DESCRIPTION
**Pull request by Dreamer451**

### CODE REVIEW

**Comment by ruslangaripov** [comment]
Currently, this pull request duplicates #244: all commits containing in this pull request (3daf031b53fdba7bed85b3402f0cf2f2166506ec, 8313043c184bb296caea8240083fc089de6c7047, de8dd324b8d6803e4ed9194d42724663128e2439, 1afe359f022ebe62ea76aacaf6eaf354a92aa049, f41800f01fbebc26e0abd5122f413501441f682e and 39856d218842d26505aacbfc3d52918eabf45846) were first introduced by #244.  But the latter was merged into the \`\`deploy'' branch[1] (and not into the \`\`master'' one).  This may confused @Dreamer451, I believe.  Kevin, did you missed some new commits here?

By the way, do we have branch description somewhere?  For example, \`\`master'' is GEDKeeper main development branch (*head*), \`\`deploy'' is for "playing" with installation, making packages, etc., and so on.

[1] https://github.com/Serg-Norseman/GEDKeeper/pull/244#event-2708567550

**Comment by Dreamer451** [comment]
That is what I get for doing anything on 3 hours sleep.  ☹️ 

No new commits--just me being ... anyway, I thought I had forgotten to make the pull request for those edits. Again, little sleep = sloppy work.

I have not gotten to the git book part where branch descriptions are made--sorry.

**Comment by Serg-Norseman** [comment]
I beg your pardon. I have complete chaos at home, a lot of repair. Therefore, I deal with the project as a nomad - in short raids without long exploring :)

Yes, the branches need to be documented somehow. Now the names and other things for them are formed on the fly, under the influence of the moment. How little I will be free, I will try to formalize this topic.

**Comment by ruslangaripov** [comment]
@Dreamer451,

> That is what I get for doing anything on 3 hours sleep

That happens  :-)

> No new commits

Should we close this pull request therefore?

> I have not gotten to the git book part where branch descriptions are made--sorry

I don't think that part even exists.  What I've meant is a textual file with additional information about each __remote__ branch purpose.  A file placed into the tree.

@Serg-Norseman,

> I will try to formalize this topic

That's just fine!

**Comment by Dreamer451** [comment]
Since this pull request (247) is a duplicate of 244, I am closing it.

**Pull request closed without merging**
