### PR TITLE
Build scripts

### PR DESCRIPTION
**Pull request by Dreamer451**
Updates to the collection of build and test scripts.

### CODE REVIEW

**Comment by ruslangaripov** [comment]
I've just noticed that this pull request still has "incorrect" commits
from #242 (604e54d15c8ac94bd408a78706df3a5381668ff6 and
1cd9897f39ae71e71aa9de63465c8b9a82cd3453)  ;-)

@Dreamer451 you didn't rollback them, did you?  :-)

**Comment by Dreamer451** [comment]
I will look through previous comments to find out what the "incorrect" commits are and why. Off the top of my head, I am not sure.

**Comment by ruslangaripov** [comment]
> to find out what the "incorrect" commits are and why

I'm talking about commits 604e54d15c8ac94bd408a78706df3a5381668ff6 and
1cd9897f39ae71e71aa9de63465c8b9a82cd3453 from the previous pull request
#242.  Both of them are presented in this pull request too.

Commit 604e54d15c8ac94bd408a78706df3a5381668ff6 adds new file
feature-deploy/gk2_win_setup.nsi into the tree, while I believe you
wanted to improve **existing** deploy/gk2_win_setup.nsi file.  As
@Serg-Norseman already said[1], you've just used a directory
(feature-deploy) instead of VCS branch (named, for example,
\`\`feature-deploy).  The same is applied to commit
1cd9897f39ae71e71aa9de63465c8b9a82cd3453.

I've suggested you already to reapplied those commits as new ones.

[1] https://github.com/Serg-Norseman/GEDKeeper/pull/242#issuecomment-534904139

**Comment by Dreamer451** [comment]
Since @Serg-Norseman was willing to ignore my mistake on using a folder instead of a branch, I was just going to leave [604e54d](https://github.com/Serg-Norseman/GEDKeeper/commit/604e54d15c8ac94bd408a78706df3a5381668ff6) and [1cd9897](https://github.com/Serg-Norseman/GEDKeeper/commit/1cd9897f39ae71e71aa9de63465c8b9a82cd3453) as they are. However, when I figure out the rollback process (which you [described](https://github.com/Serg-Norseman/GEDKeeper/pull/243#commitcomment-35251995) earlier) I certainly could roll them back and submit them properly. If @Serg-Norseman agrees, it will be done.

**Comment by Serg-Norseman** [comment]
I apologize. Although for the third week now I have been on a long vacation, I have very little time - I solve household issues and repair the apartment. Therefore, I can’t delve into what is happening on the topics of the project. I expect to be released approximately in a week or two.

Nevertheless, it is also possible that any next day I will be able to interrupt current worries and suddenly solve questions on the project.

**Comment by Dreamer451** [comment]
We all understand real life. Good luck on repairing your apartment! I have household repairs to do also, and I am not looking forward to it...

**Comment by Dreamer451** [comment]
Try as I might, I could not get your process to work for me so I brought up [SourceTree](https://sourcetreeapp.com/) to try fixing it. A little success, but not back to clean (remove pull request [242](https://github.com/Serg-Norseman/GEDKeeper/pull/242)). If I cannot figure this out in the next day or two, I am going to delete my repository and re-clone. Drastic, but I am not sure what to do.  :(

**Comment by ruslangaripov** [comment]
> @Dreamer451 closed this ...

But why?  There are some interesting changes here, I believe.

> I could not get your process to work for me

I can try to help you via GEDKeeper's gitter chat.  We just need to agree on time.  Currently (4:20 am UTC) I'm available there.

> I am going to delete my repository and re-clone

Be careful, don't lose your changes.

**Comment by Dreamer451** [comment]
I would not lose my changes--I have a copy in a safe location. I would love to get your interactive feedback via Gitter chat. If I have the time correct, then you are about 16 hours behind me. So pick a time and I'll be there.

**Comment by ruslangaripov** [comment]
> Dreamer451 closed this

#244 partially replaces this pull request (swallow 6a4bee61c26ec415ab8bbe7550be80fdffe3db08, a7b6f2be5b0070a24fe886d4938d380aa9311ffc, 3633040c14086013584f5cef3cd058679fc702d4, 7ffe4422d982eab791ba7d3655d8817f90dae3ef, ccbc95913a23db437c318115d0f68fa33ed2cc02 and e78e12b2b1a7db872c23674a6543eb05c3443308 up).

**Pull request closed without merging**
